# import Library

In [1]:
import numpy as np
import pandas as pd

In [71]:
data = pd.read_csv("Vina.csv")

In [3]:
data.head()

tahun nama_provinsi         nama_destinasi_wisata nama_kabupaten_kota  \
0   2014   DKI Jakarta                   TIJA Ancol*       Jakarta Utara   
1   2014   DKI Jakarta   Taman Mini Indonesia Indah*       Jakarta Timur   
2   2014   DKI Jakarta       T. Marga Satwa Ragunan*     Jakarta Selatan   
3   2014   DKI Jakarta              Monumen Nasional       Jakarta Pusat   
4   2014   DKI Jakarta               Museum Nasional       Jakarta Pusat   

     jumlah  
0  16085604  
1   4587735  
2   4100249  
3   1135944  
4    245848

In [4]:
data.tail()

tahun nama_provinsi            nama_destinasi_wisata nama_kabupaten_kota  \
138   2018   DKI Jakarta                Kepulauan Seribu        Jakarta Utara   
139   2018   DKI Jakarta                PBB Setu Babakan      Jakarta Selatan   
140   2018   DKI Jakarta                  Museum Prasasti       Jakarta Pusat   
141   2018   DKI Jakarta                      Planetarium       Jakarta Pusat   
142   2018   DKI Jakarta  Rumah Si Pitung (Situs Marunda)       Jakarta Utara   

     jumlah  
138  662420  
139  437766  
140   12356  
141  212759  
142   37732

In [5]:
data.size

715

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143 entries, 0 to 142
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   tahun                  143 non-null    int64 
 1   nama_provinsi          143 non-null    object
 2   nama_destinasi_wisata  143 non-null    object
 3   nama_kabupaten_kota    143 non-null    object
 4   jumlah                 143 non-null    int64 
dtypes: int64(2), object(3)
memory usage: 5.7+ KB


In [7]:
data.empty

False

# Merubah type data

In [72]:
def make_label(nama_kabupaten_kota):
    if nama_kabupaten_kota == "Jakarta Utara":
        return 1
    elif nama_kabupaten_kota == "Jakarta Selatan":
        return 2
    else:
        return 0

In [62]:
data.head()

tahun nama_provinsi         nama_destinasi_wisata nama_kabupaten_kota  \
0   2014   DKI Jakarta                   TIJA Ancol*       Jakarta Utara   
1   2014   DKI Jakarta   Taman Mini Indonesia Indah*       Jakarta Timur   
2   2014   DKI Jakarta       T. Marga Satwa Ragunan*     Jakarta Selatan   
3   2014   DKI Jakarta              Monumen Nasional       Jakarta Pusat   
4   2014   DKI Jakarta               Museum Nasional       Jakarta Pusat   

     jumlah  
0  16085604  
1   4587735  
2   4100249  
3   1135944  
4    245848

In [73]:
data["Nama Kabupaten Kota"]=data["nama_kabupaten_kota"].apply(make_label)
data

tahun nama_provinsi            nama_destinasi_wisata nama_kabupaten_kota  \
0     2014   DKI Jakarta                      TIJA Ancol*       Jakarta Utara   
1     2014   DKI Jakarta      Taman Mini Indonesia Indah*       Jakarta Timur   
2     2014   DKI Jakarta          T. Marga Satwa Ragunan*     Jakarta Selatan   
3     2014   DKI Jakarta                 Monumen Nasional       Jakarta Pusat   
4     2014   DKI Jakarta                  Museum Nasional       Jakarta Pusat   
..     ...           ...                              ...                 ...   
138   2018   DKI Jakarta                Kepulauan Seribu        Jakarta Utara   
139   2018   DKI Jakarta                PBB Setu Babakan      Jakarta Selatan   
140   2018   DKI Jakarta                  Museum Prasasti       Jakarta Pusat   
141   2018   DKI Jakarta                      Planetarium       Jakarta Pusat   
142   2018   DKI Jakarta  Rumah Si Pitung (Situs Marunda)       Jakarta Utara   

       jumlah  Nama Kabupaten Kota  
0    16085604                    1  
1     4587735                    0  
2     4100249                    2  
3     1135944                    0  
4      245848                    0  
..        ...                  ...  
138    662420                    1  
139    437766                    2  
140     12356                    0  
141    212759                    0  
142     37732                    1  

[143 rows x 6 columns]

In [80]:
def make_label(nama_destinasi_wisata):
    if nama_destinasi_wisata == "Planetarium":
        return 1
    elif nama_destinasi_wisata == "Museum Prasasti":
        return 2
    else:
        return 0

In [81]:
data["Nama Destinasi Wisata"]=data["nama_destinasi_wisata"].apply(make_label)
data

tahun nama_provinsi            nama_destinasi_wisata nama_kabupaten_kota  \
0     2014   DKI Jakarta                      TIJA Ancol*       Jakarta Utara   
1     2014   DKI Jakarta      Taman Mini Indonesia Indah*       Jakarta Timur   
2     2014   DKI Jakarta          T. Marga Satwa Ragunan*     Jakarta Selatan   
3     2014   DKI Jakarta                 Monumen Nasional       Jakarta Pusat   
4     2014   DKI Jakarta                  Museum Nasional       Jakarta Pusat   
..     ...           ...                              ...                 ...   
138   2018   DKI Jakarta                Kepulauan Seribu        Jakarta Utara   
139   2018   DKI Jakarta                PBB Setu Babakan      Jakarta Selatan   
140   2018   DKI Jakarta                  Museum Prasasti       Jakarta Pusat   
141   2018   DKI Jakarta                      Planetarium       Jakarta Pusat   
142   2018   DKI Jakarta  Rumah Si Pitung (Situs Marunda)       Jakarta Utara   

       jumlah  Nama Kabupaten Kota  Nama Destinasi Wisata  
0    16085604                    1                      0  
1     4587735                    0                      0  
2     4100249                    2                      0  
3     1135944                    0                      0  
4      245848                    0                      0  
..        ...                  ...                    ...  
138    662420                    1                      0  
139    437766                    2                      0  
140     12356                    0                      2  
141    212759                    0                      1  
142     37732                    1                      0  

[143 rows x 7 columns]

In [83]:
def make_label(nama_provinsi):
    if nama_provinsi == "DKI Jakarta":
        return 1
    elif nama_provinsi == "":
        return 2
    else:
        return 0

In [84]:
data["Nama Provinsi"]=data["nama_provinsi"].apply(make_label)
data

tahun nama_provinsi            nama_destinasi_wisata nama_kabupaten_kota  \
0     2014   DKI Jakarta                      TIJA Ancol*       Jakarta Utara   
1     2014   DKI Jakarta      Taman Mini Indonesia Indah*       Jakarta Timur   
2     2014   DKI Jakarta          T. Marga Satwa Ragunan*     Jakarta Selatan   
3     2014   DKI Jakarta                 Monumen Nasional       Jakarta Pusat   
4     2014   DKI Jakarta                  Museum Nasional       Jakarta Pusat   
..     ...           ...                              ...                 ...   
138   2018   DKI Jakarta                Kepulauan Seribu        Jakarta Utara   
139   2018   DKI Jakarta                PBB Setu Babakan      Jakarta Selatan   
140   2018   DKI Jakarta                  Museum Prasasti       Jakarta Pusat   
141   2018   DKI Jakarta                      Planetarium       Jakarta Pusat   
142   2018   DKI Jakarta  Rumah Si Pitung (Situs Marunda)       Jakarta Utara   

       jumlah  Nama Kabupaten Kota  Nama Destinasi Wisata  Nama Provinsi  
0    16085604                    1                      0              1  
1     4587735                    0                      0              1  
2     4100249                    2                      0              1  
3     1135944                    0                      0              1  
4      245848                    0                      0              1  
..        ...                  ...                    ...            ...  
138    662420                    1                      0              1  
139    437766                    2                      0              1  
140     12356                    0                      2              1  
141    212759                    0                      1              1  
142     37732                    1                      0              1  

[143 rows x 8 columns]

In [85]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143 entries, 0 to 142
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   tahun                  143 non-null    int64 
 1   nama_provinsi          143 non-null    object
 2   nama_destinasi_wisata  143 non-null    object
 3   nama_kabupaten_kota    143 non-null    object
 4   jumlah                 143 non-null    int64 
 5   Nama Kabupaten Kota    143 non-null    int64 
 6   Nama Destinasi Wisata  143 non-null    int64 
 7   Nama Provinsi          143 non-null    int64 
dtypes: int64(5), object(3)
memory usage: 9.1+ KB


In [88]:
data["Nama Kabupaten Kota"].head()

0    1
1    0
2    2
3    0
4    0
Name: Nama Kabupaten Kota, dtype: int64

In [91]:
data[["Nama Destinasi Wisata","Nama Provinsi","jumlah"]].head()

Nama Destinasi Wisata  Nama Provinsi    jumlah
0                      0              1  16085604
1                      0              1   4587735
2                      0              1   4100249
3                      0              1   1135944
4                      0              1    245848

In [92]:
from sklearn.model_selection import train_test_split

In [93]:
x_train, x_test, y_train, y_test = train_test_split(data[["Nama Destinasi Wisata","Nama Provinsi","jumlah"]],data["Nama Kabupaten Kota"])

In [94]:
x_train

Nama Destinasi Wisata  Nama Provinsi    jumlah
44                       0              1    163775
70                       0              1   5702950
78                       0              1    202887
43                       0              1     72143
98                       0              1     18545
..                     ...            ...       ...
118                      0              1     14571
68                       0              1    225663
56                       0              1    234500
52                       0              1  16661517
66                       0              1    357275

[107 rows x 3 columns]

In [95]:
y_train

44     0
70     0
78     0
43     1
98     0
      ..
118    0
68     0
56     0
52     1
66     1
Name: Nama Kabupaten Kota, Length: 107, dtype: int64

In [96]:
x_test

Nama Destinasi Wisata  Nama Provinsi    jumlah
21                       0              1    148118
108                      0              1   4483847
62                       0              1    439818
109                      0              1   3681968
129                      0              1     11693
9                        0              1    116083
126                      0              1   5455788
97                       0              1    312081
115                      0              1     17602
27                       0              1    187386
136                      0              1     65448
131                      0              1     41805
110                      0              1   1115360
79                       0              1    373521
4                        0              1    245848
135                      0              1     18711
87                       0              1  10359661
26                       0              1     49308
73                       0              1    256825
127                      0              1   1945747
17                       0              1  15848956
1                        0              1   4587735
60                       0              1     22799
50                       0              1    338681
120                      0              1     38592
7                        0              1     50612
121                      0              1     26543
94                       0              1     34299
28                       0              1     20707
30                       0              1     31956
128                      0              1    263171
18                       0              1   4726273
20                       0              1   1418469
61                       0              1    166739
0                        0              1  16085604
105                      0              1     35713

In [97]:
y_test

21     0
108    0
62     0
109    2
129    2
9      0
126    2
97     0
115    1
27     0
136    1
131    0
110    0
79     0
4      0
135    0
87     1
26     0
73     0
127    0
17     1
1      0
60     1
50     2
120    1
7      0
121    1
94     0
28     0
30     1
128    0
18     0
20     0
61     0
0      1
105    1
Name: Nama Kabupaten Kota, dtype: int64

# BernoulliNB

In [98]:
from sklearn import naive_bayes

In [99]:
clf = naive_bayes.BernoulliNB()

In [100]:
clf.fit(x_train, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [101]:
clf.predict(x_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [102]:
clf.score(x_train,y_train) # data training = 80%

0.5046728971962616

In [103]:
clf.score(x_test,y_test) #data testing = 20%

0.6111111111111112

# GaussianNB

In [104]:
from sklearn.naive_bayes import GaussianNB

In [105]:
modelnb = GaussianNB()

In [106]:
nbtrain = modelnb.fit(x_train,y_train)  # data training 80%
nbtrain.class_count_

array([54., 33., 20.])

In [107]:
modelnb.predict(x_test)

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int64)

In [108]:
modelnb.score(x_train,y_train) # data training 80%

0.5046728971962616

In [109]:
modelnb.score(x_test,y_test) # data testing 20%

0.6944444444444444